title: OpenStreetMap Nederland
description: OpenStreetMap Nederland community website

markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

twitter:
  username: osm_be
social:
  name: OpenStreetMap Nederland
  links:
    - https://github.com/osmnl

url: https://osmnl.github.io/
baseurl: ""

exclude:
  - INSTALL.md
  - package.json
  - package-lock.json
  - node_modules/
  - .cache/
  - _javascript/

future: true
permalink: /:categories/:year/:month/:day/:title:output_ext
feed:
  collections:
    - events

collections:
  # category:
  #   output: true
  #   permalink: /:collection/:name:output_ext
  events:
    output: true
  #   permalink: /:categories/:year/:month/:day/:title:output_ext
